### ISSUE TITLE
Remove generated files

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-epo#1]
@vyhuholl, these files/folders are generated during build and must not be in the repo:
autom4te.cache/
modes/
INSTALL
Makefile
Makefile.in
aclocal.m4
ap_include.am
apertium-epo.pc
config.log
config.status
configure
*.mode
*.att.gz
*.bin
install-sh
missing

Please wipe them and remove them from history - as in, rewrite history so that these files never existed in the repo. Since you've done the only commit, you can recreate the repo with only the non-generated files, then `git push -f` to rewrite history.

**Comment by vyhuholl** [comment]
done

**Comment by TinoDidriksen** [comment]
Not done. They're still in history. And now you've added another bad file: .DS_Store

Plus, you removed Makefile.am and configure.ac which ARE needed. I did not list those, on purpose.

**Comment by TinoDidriksen** [comment]
Fixed history for you. Clone it again.
