### ISSUE TITLE
Parser Error on this data pack

### ISSUE THREAD

**Issue by Hypperz** [apertium/apertium-epo#2]
> apertium-validate-dictionary apertium-epo.epo.dix
> apertium-epo.epo.dix:124: parser error : Extra content at the end of the document
> <pardef n="abela__S">
> ^
> apertium-epo.epo.dix:124: parser error : Extra content at the end of the document
> <pardef n="abela__S">
> ^
> make: *** [epo.automorf.bin] Error 1

Seems to think it has an illegal character in the file, but I can't see it on the noted line.

**Comment by mr-martian** [comment]
The issue is a few lines earlier in the file where it says `</dictionary>`.

This entire dictionary file is mostly wrong and probably needs to be rewritten / imported from the Esperanto pairs.

**Comment by mr-martian** [comment]
Fixed in 27df7c5
